config/routes.rb
Rails.application.routes.draw do
  resources :registry
  resources :participant
  resources :coordinator
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
    has_many :registry
    has_many :participants
end

app/models/participant.rb
class Participant < ApplicationRecord
    has_one :coordinator
    has_many :registry
end

app/models/registry.rb
class Registry < ApplicationRecord
    has_many :coordinators
    has_many :participants, :through => :coordinators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/coordinator_controller.rb
class CoordinatorController < ApplicationController
#before_action :coordinator, only: [:show, :edit, :update, :destroy]
#get all coordinators
    def index
        @coordinators = Coordinator.all
        respond_to do |format|
            format.html { render :coordinator  }
        end
    end

#get One coordinator
    def show
        @coordinator = Coordinator.find(params[:id])
        respond_to do |format|
            format.html { render :coordinator_view  }
        end
    end
    
#get all coordinators for a coordinator
    def show_coordinators
        @coordinator = Coordinator.find(params[:id])
        respond_to do |format|
            format.html { render :coordinator  }
        end
    end

#Change Coordinator information
    def edit
        @coordinator = Coordinator.find(params[:id])
        respond_to do |format|
            format.html { render :coordinator_edit  }
          end
    end

#New coordinator form
    def new
        @coordinator = Coordinator.new
        respond_to do |format|
            format.html { render :coordinator_new  }
        end
    end

#Save new Coordinator to DB
    def create
        @coordinator = Coordinator.new(coordinator_params)
        respond_to do |format|
            if @coordinator.save
              format.html { redirect_to @coordinator, notice: 'Coordinator was successfully created.' }
              format.json { render :show, status: :created, location: coordinator }
            else
              format.html { render :new }
              format.json { render json: @coordinator.errors, status: :unprocessable_entity }
            end
          end
    end

#Update Coordinator information
    def update
        @coordinator = Coordinator.find(params[:id])
        if @coordinator.update(coordinator_params)
            redirect_to coordinator_path
        else
            render :coordinator_edit
        end
    end

#delete Coordinator
    def destroy
        @coordinator = Coordinator.find(params[:id])
        @coordinator.destroy
        redirect_to coordinator_index_path
    end

    def coordinator_param
        params.require(:coordinator).permit(:name, :email, :phone_number, :coordinator_id)
    end

    private
    def coordinator_params
        params.permit(:name, :email, :phone_number, :coordinator_id)
    end
end

app/controllers/participant_controller.rb
class ParticipantController < ApplicationController
 #get all participants   
    def index
        @participants = Participant.all
        respond_to do |format|
            format.html { render :participant  }
          end
    end
#get 1 participant
    def show
        @participant = Participant.find(params[:id])
        respond_to do |format|
            format.html { render :participant_view  }
        end
    end

# #get all participants for a coordinator
def show_participants
    @participant = Participant.find(params[:id])
    respond_to do |format|
        format.html { render :participants  }
    end
end

#Create a new participant form
    def new
        @participant = Participant.new
        respond_to do |format|
            format.html { render :participant_new  }
        end
    end
    
#Edit participant information
    def edit
        @participant = Participant.find(params[:id])
        respond_to do |format|
            format.html { render :participant_edit  }
          end
    end

#Save participant in DB
    def create
        @participant = Participant.new(participant_params)
        respond_to do |format|
            if @participant.save
              format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
              format.json { render :show, status: :created, location: participant }
            else
              format.html { render :new }
              format.json { render json: @participant.errors, status: :unprocessable_entity }
            end
        end
    end

    #Update participant information
    def update
        @participant = Participant.find(params[:id])
        if @participant.update(participant_params)
            redirect_to participant_path
        else
            render :participant_edit
        end
    end

    #delete participant
    def destroy
        @participant = Participant.find(params[:id])
        @participant.destroy
        redirect_to participant_index_path
    end

    def participant_param
        params.require(:participant).permit(:name, :email, :gender, :date_of_birth, :phone_number, :method_of_contact, :remarks, :coordinators_id)
    end

    private
    def participant_params
      params.permit(:name, :email, :gender, :date_of_birth, :phone_number, :method_of_contact, :remarks, :coordinators_id)
    end
end

app/controllers/registry_controller.rb
class RegistryController < ApplicationController
#Get all registries
    def index
        @registries = Registry.all
    end
#Get a registry
    def show
        @registry = Registry.find(params[:id])
        respond_to do |format|
            format.html { render :registry_view  }
        end
    end
#New registry form
    def new
        @registry = Registry.new
        respond_to do |format|
            format.html { render :registry_new  }
        end
    end
#Save new registry to DB
    def create
        @registry = Registry.new(registry_params)
        respond_to do |format|
            if @registry.save
              format.html { redirect_to @registry, notice: 'Registry was successfully created.' }
              format.json { render :show, status: :created, location: registry }
            else
              format.html { render :new }
              format.json { render json: @registry.errors, status: :unprocessable_entity }
            end
        end
    end
#Edit registry
    def edit
        @registry = Registry.find(params[:id])
        respond_to do |format|
            format.html { render :registry_edit  }
        end
    end
#Update registry information
    def update
        @registry = Registry.find(params[:id])
        if @registry.update(registry_params)
            redirect_to registry_path
        else
            render :registry_edit
        end
    end
#delete registry
    def destroy
        @registry = Registry.find(params[:id])
        @registry.destroy
        redirect_to registry_index_path
    end
    
  private
    def registry_params
      params.permit(:name, :location, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registry_helper.rb
module RegistryHelper
end

app/views/coordinator/coordinator.html.erb
<div class="container">
<h1 class="text-danger">Coordinator List</h1>
<%= link_to "Add New Coordinator", new_coordinator_path %>
<% if @coordinators.blank? %>
<p>There are no coordinators in our system at the moment.</p>
<% else %>
<table class="table table-striped">
<thead>
<th>Coordinator Name</th>
<th>Coordinator Email</th>
<th>Coordinator Phone</th>
<th>Options</th>
</thead>
  <% @coordinators.each do |coordinator| %>
  <tr>
    <td><%= link_to @participant.coordinators_id.name, :action => "show_participants" , :id => @participant.coordinators_id.id %></td>
    <td><%= coordinator.email %></td>
    <td><%= coordinator.phone_number %></td>
    <td>
    <%= link_to "Edit Info", edit_coordinator_path(coordinator) %>
    <%= link_to "Remove", coordinator, method: :delete, data: { confirm: "Are you sure you want to delete this coordinator?" } %>
    </td>
  </tr>
    <% end %>
</table>
 <% end %>
</div>

app/views/coordinator/coordinator_edit.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<%= form_for @coordinator do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control form-control-sm", name:"name" %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email, class:"form-control form-control-sm", name:"email" %>
</div>
<div>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class:"form-control form-control-sm", name:"phone_number" %>
</div>
<div>
<hr />
  <%= f.submit :Update, class:"btn btn-sm btn-success" %>
</div>
<% end %>
<hr />
<%= link_to 'Back to Coordinators Table' ,{:action => 'index'} %>
</div>
</div>

app/views/coordinator/coordinator_new.html.erb
<div class="container">
<h1 class="text-info">Add New Coordinator</h1>
<div class="col-lg-4 col-md-4 col-xs-10">
  <form action="/coordinator" class="form-horizontal" method="POST" role="form">
    <div class="form-group">
      <label class="control-label" for="name">Coordinator Name</label>
      <input type="text" class="form-control" name="name" id="name" required>
    </div>
    <div class="form-group">
      <label class="control-label" for="email">Coordinator Email</label>
      <input type="text" class="form-control" name="email" id="email" required>
    </div>
    <div class="form-group">
    <label class="control-label" for="phone_number">Coordinator Phone Number</label>
    <input type="tel" class="form-control" name="phone_number" id="phone_number" required>
    </div>
    <div class="form-group">
    <button type="submit" class="btn btn-success">Submit</button>
    <hr />
    <%= link_to 'Coordinators Table' ,{:action => 'index'} %>
    </div>
  </form>
</div>
</div>

app/views/coordinator/coordinator_view.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<%= form_for @coordinator do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control form-control-sm", name:"name", :disabled => true %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email, class:"form-control form-control-sm", name:"email", :disabled => true %>
</div>
<div>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class:"form-control form-control-sm", name:"phone_number", :disabled => true %>
</div>
<% end %>
<hr />
<%= link_to 'Coordinator Table', {:action => 'index'} %>
</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">

<!-- BRAND -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#alignment-example" aria-expanded="false">
<span class="sr-only">Sci-Track</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%# <a class="navbar-brand" href="#">Sci-Track</a> %>
<%= link_to 'Sci-Track', registry_index_path, class: 'navbar-brand' %>
</div>

<!-- COLLAPSIBLE NAVBAR -->
<div class="collapse navbar-collapse" id="alignment-example">

<!-- Links -->
<ul class="nav navbar-nav">
<li class="active"><a href="/registry">Registries <span class="sr-only">(current)</span></a></li>
<li><a href="/coordinator">Coordinators</a></li>
<li><a href="/participant">Participants</a></li>
</ul>

<!-- Button -->
<button type="button" class="btn btn-default navbar-btn navbar-right">Sign in</button>

</div>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scitrak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/participant/participant.html.erb
<div class="container">
<h1 class="text-danger">Participants List</h1>
<%= link_to "Add New Participant", new_participant_path %>
<table class="table table-striped">
<thead>
<th>Name</th>
<th>Email</th>
<th>Gender</th>
<th>Date of Birth</th>
<th>Phone Number</th>
<th>Method of Contact</th>
<th>Remarks</th>
<th>Options</th>
</thead>
  <% @participants.each do |participant| %>
  <tr>
    <td><%= link_to participant.name, participant_path(participant) %></td>
    <td><%= participant.email %></td>
        <td><%= participant.gender %></td>
            <td><%= participant.date_of_birth %></td>
                <td><%= participant.phone_number %></td>
                    <td><%= participant.method_of_contact %></td>
                        <td><%= participant.remarks %></td>
                            
    <td>
    <%= link_to "Edit Info", edit_participant_path(participant) %>
    <%= link_to "Remove", participant, method: :delete, data: { confirm: "Are you sure you want to delete this participant?" } %>
    </td>
  </tr>
    <% end %>
</table>
</div>

app/views/participant/participant_edit.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<%= form_for @participant do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control form-control-sm", name:"name" %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email, class:"form-control form-control-sm", name:"email" %>
</div>
<div>
  <%= f.label :gender %>
  <%= f.text_field :gender, class:"form-control form-control-sm", name:"gender" %>
</div>
<div>
  <%= f.label :date_of_birth %>
  <%= f.text_field :date_of_birth, class:"form-control form-control-sm", name:"date_of_birth" %>
</div>
<div>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class:"form-control form-control-sm", name:"phone_number" %>
</div>
<div>
  <%= f.label :method_of_contact %>
  <%= f.text_field :method_of_contact, class:"form-control form-control-sm", name:"method_of_contact" %>
</div>
<%
=begin%>
 <div>
  <%= f.label :Coordinator %>
  <%= f.text_field :Coordinator, class:"form-control form-control-sm", name:"Coordinator" %>
</div> 
<%
=end%>
<div>
  <%= f.label :remarks %>
  <%= f.text_area :remarks, class:"form-control form-control-sm", name:"remarks" %>
</div>
<div>
<br />
  <%= f.submit :Update, class:"btn btn-sm btn-success" %>
  <hr />
  <%= link_to 'Back', {:action => 'index'} %>
</div>
<% end %>
</div>
</div>

app/views/participant/participant_new.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<h1 class="text-info">Add New Participant</h1>
  <form action="/participant" class="form-horizontal" method="POST" role="form">
    <div class="form-group">
      <label class="control-label" for="name">Name</label>
      <input type="text" class="form-control" name="name" id="name" required>
    </div>
    <div class="form-group">
      <label class="control-label" for="email">Email</label>
      <input type="text" class="form-control" name="email" id="email" required>
    </div>
    <div class="form-group">
    <p style="margin-bottom: 0px;"><strong class="control-label text-bold" for="gender">Gender</strong></p>
      <div class="radio-inline">
        <label><input type="radio" name="gender" value="Male" checked>Male</label>
      </div>
      <div class="radio-inline">
        <label><input type="radio" name="gender" value="Female">Female</label>
      </div>
    </div>
        <div class="form-group">
      <label class="control-label" for="date_of_birth">Date of Birth</label>
      <input type="text" class="form-control" name="date_of_birth" id="date_of_birth" required>
      <small class="text-muted">format YYYY-MM-DD</small>
    </div>
    <div class="form-group">
    <label class="control-label" for="phone_number">Phone Number</label>
    <input type="tel" class="form-control" name="phone_number" id="phone_number" required>
    </div>
    <div class="form-group">
    <p style="margin-bottom: 0px;"><strong class="control-label" for="method_of_contact">Method of Contact</strong></p>
      <div class="radio-inline">
        <label><input type="radio" name="method_of_contact" value="Email" checked>Email</label>
      </div>
      <div class="radio-inline">
        <label><input type="radio" name="method_of_contact" value="Phone">Phone</label>
      </div>
    </div>
    <div class="form-group">
    <button type="submit" class="btn btn-success">Submit</button>
    <hr />
    <%= link_to 'Back' ,{:action => 'index'} %>
    </div>
  </form>
</div>
</div>

app/views/participant/participant_view.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<%= form_for @participant do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control form-control-sm", name:"name", :disabled => true %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email, class:"form-control form-control-sm", name:"email", :disabled => true %>
</div>
<div>
  <%= f.label :gender %>
  <%= f.text_field :gender, class:"form-control form-control-sm", name:"gender", :disabled => true %>
</div>
<div>
  <%= f.label :date_of_birth %>
  <%= f.text_field :date_of_birth, class:"form-control form-control-sm", name:"date_of_birth", :disabled => true %>
</div>
<div>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class:"form-control form-control-sm", name:"phone_number", :disabled => true %>
</div>
<div>
  <%= f.label :method_of_contact %>
  <%= f.text_field :method_of_contact, class:"form-control form-control-sm", name:"method_of_contact", :disabled => true %>
</div>
<%
=begin%>
 <div>
  <%= f.label :Coordinator %>
  <%= f.text_field :Coordinator, class:"form-control form-control-sm", name:"Coordinator", :disabled => true %>
</div> 
<%
=end%>
<div>
  <%= f.label :remarks %>
  <%= f.text_area :remarks, class:"form-control form-control-sm", name:"remarks", :disabled => true %>
</div>
<% end %>
<hr />
<%= link_to 'Participant Table', {:action => 'index'} %>
</div>
</div>

app/views/participant/participants.html.erb
<div class="container">
<h1 class="text-danger">Participants List</h1>
<%= link_to "Add New Participant", new_participant_path %>
<table class="table table-striped">
<thead>
<th>Name</th>
<th>Email</th>
<th>Gender</th>
<th>Date of Birth</th>
<th>Phone Number</th>
<th>Method of Contact</th>
<th>Remarks</th>
<th>Options</th>
</thead>
  <% @coordinator.participants.each do |participant| %>
  <tr>
    <td><%= link_to participant.name, participant_path(participant) %></td>
    <td><%= participant.email %></td>
        <td><%= participant.gender %></td>
            <td><%= participant.date_of_birth %></td>
                <td><%= participant.phone_number %></td>
                    <td><%= participant.method_of_contact %></td>
                        <td><%= participant.remarks %></td>
                            
    <td>
    <%= link_to "Edit Info", edit_participant_path(participant) %>
    <%= link_to "Remove", participant, method: :delete, data: { confirm: "Are you sure you want to delete this participant?" } %>
    </td>
  </tr>
    <% end %>
</table>
</div>

app/views/registry/index.html.erb
<div class="container">
<h1 class="text-danger">Registries</h1>
<%= link_to "Add New Registry", new_registry_path %>
<table class="table table-striped">
<thead>
<th>Registry Name</th>
<th>Registry Location</th>
<th>Registry State</th>
<th>Options</th>
</thead>
  <% @registries.each do |registry| %>
  <tr> 
    <td><%= link_to registry.name, registry_path(registry) %></td>
    <td><%= registry.location %></td>
    <td><%= registry.state %></td>
    <td>
    <%= link_to "Edit Info", edit_registry_path(registry) %>
    <%= link_to "Remove", registry, method: :delete, data: { confirm: "Are you sure you want to delete this registry?" } %>
    </td>
  </tr>
    <% end %>
</table>
</div>

app/views/registry/registry_edit.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<%= form_for @registry do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control form-control-sm", name:"name" %>
</div>
<div>
  <%= f.label :location %>
  <%= f.text_field :location, class:"form-control form-control-sm", name:"location" %>
</div>
<div>
  <%= f.label :state %>
  <%
=begin%>
 <%= f.text_field :state, class:"form-control form-control-sm", name:"state" %> 
<%
=end%>
  <%= f.collection_select :id, Registry.all, :id, :state, {class:'form-control form-control-sm'} %>
</div>
<div>
<hr />
  <%= f.submit :Update, class:"btn btn-sm btn-success" %>
</div>
<% end %>
</div>
</div>

app/views/registry/registry_new.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
  <form action="/registry" class="form-horizontal" method="POST" role="form">
    <div class="form-group">
      <label class="control-label" for="name">Registry Name</label>
      <input type="text" class="form-control" name="name" id="name" required>
    </div>
    <div class="form-group">
      <label class="control-label" for="location">Registry Location</label>
      <input type="text" class="form-control" name="location" id="location" required>
    </div>
    <div class="form-group">
    <label class="control-label" for="state">Registry State</label>
      <div class="radio">
        <label><input type="radio" name="state" value="Open" checked>Open</label>``
      </div>
      <div class="radio">
        <label><input type="radio" name="state" value="Closed">Closed</label>
      </div>
    </div>
    <div class="form-group">
    <hr />
    <button type="submit" class="btn btn-success">Submit</button>
      <hr />
    <%= link_to 'Back to Registry Table' ,{:action => 'index'} %>
    </div>
  </form>
</div>
</div>

app/views/registry/registry_view.html.erb
<div class="container">
<div class="col-lg-4 col-md-4 col-xs-10">
<%= form_for @registry do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, class:"form-control form-control-sm", name:"name", :disabled => true %>
</div>
<div>
  <%= f.label :location %>
  <%= f.text_field :location, class:"form-control form-control-sm", name:"location", :disabled => true %>
</div>
<div>
  <%= f.label :state %>
  <%= f.text_field :state, class:"form-control form-control-sm", name:"state", :disabled => true %>
</div>
<% end %>
<hr />
<%= link_to 'Back', {:action => 'index'} %>
</div>
</div>